### ISSUE TITLE
Requirement Elicitation from the available SOW by - Daya

### ISSUE THREAD

**Issue by sshaikh4** [binny-chopra/smarter-university-system#14]
Activity for Create User Stories #6 

Daya will be sharing a list of requirements from the SOW available.

**Comment by Daya-Sagar2357** [comment]
1. Student should be able to log in to the system so that they can effectively manage their classes.
2. Student should be able to search and view available classes and their syllabuses for informed enrollment decisions.
3. Student should be able to sign up for open classes (not exceeding the maximum enrollment) to secure needed spots.
4. Student should be able to submit prerequisite-based enrollment requests (remote and online) for course access.
5. Student should be able to access grades for academic progress tracking.
6. Student should be able to view team assignments for effective collaboration.

**Comment by Daya-Sagar2357** [comment]
Marking this activity as closed, as the requirements for the Student role has been listed out.
