### ISSUE TITLE
Streamlining Business Requirements into User Stories - Shabnam

### ISSUE THREAD

**Issue by binny-chopra** [binny-chopra/smarter-university-system#24]
Epic #6 - It is important to analyze and convert the scenarios outlined in the Statement of Work (SOW) into actionable system requirements for automating lecture processes and tracking student performance at the University of Higher Learning (UHL)

**Comment by sshaikh4** [comment]
Basis the requirements I had submitted for an **Admin** role, below is the re-phrased **user stories** for the same:

1. As an admin, I want to be able to let students sign up for classes if available, so that the students are able to enroll for classes with ease
2. As an admin, I want to be able to maintain the database for available classes, so that the enrollment count is known
3. As an admin, I want to maintain the classes for the same sections based on the geographical location, so that I can manage the classes efficiently
4. As an admin, I want to ensure that classes are remote video capable, so that students can participate in class remotely
5. As an admin, I want to receive alert notifications via email when a course is 80% or more full, so that I can take appropriate actions to manage class enrollments
6. As an admin, I want to be able to monitor the status of all courses, including the number of enrolled students and maximum capacities, so that I can ensure efficient course management
7. As an admin, I want to have the ability to add or remove students from classes, so that I can address enrollment issues
8. As an admin, I want to handle submitted enrollment requests from students who do not meet course prerequisites by approving or denying their requests, so that I can manage class enrollments effectively
9. As an admin, I want to access each instructor's information including their names, email address, education details and the list of courses they have taught, so that I can have a complete overview of the teaching staff
10. As an admin, I want to manage the database for SUS, so that it serves as the primary database for grades

**Comment by sshaikh4** [comment]
Marking this activity as closed since the user stories for Admin are created and ready for next steps.
