### ISSUE TITLE
Streamlining Business Requirements into User Stories - Daya

### ISSUE THREAD

**Issue by binny-chopra** [binny-chopra/smarter-university-system#26]
Epic #6 - It is important to analyze and convert the scenarios outlined in the Statement of Work (SOW) into actionable system requirements for automating lecture processes and tracking student performance at the University of Higher Learning (UHL)

**Comment by Daya-Sagar2357** [comment]
1) As a student, I should be able to log in to the system so that I can effectively manage my classes.
2) As a student, I should be able to search and view available classes and their syllabuses so that I can make informed enrollment decisions.
3) As a student, I should be able to sign up for open classes (not exceeding the maximum enrollment) so that I can secure needed spots.
4) As a student, I should be able to submit prerequisite-based enrollment requests (remote and online) so that I can have course access.
5) As a student, I should be able to access grades so that I can track my academic progress.
6) As a student, I should be able to view team assignments so that I can practise effective collaboration.

**Comment by Daya-Sagar2357** [comment]
Marking this activity as closed, since the user stories for the Student role has been generated from the corresponding user stories, and is ready for next steps.
