### ISSUE TITLE
Streamlining Business Requirements into User Stories - Janesh

### ISSUE THREAD

**Issue by binny-chopra** [binny-chopra/smarter-university-system#27]
Epic #6  - It is important to analyze and convert the scenarios outlined in the Statement of Work (SOW) into actionable system requirements for automating lecture processes and tracking student performance at the University of Higher Learning (UHL)

**Comment by Jhasija9** [comment]
Here are user stories for Teaching Assistant:
As a Teaching Assistant, I should be able to divide students into teams so that students can collaborate with each other for team projects.
As a Teaching Assistant, I should be able to name teams so that students can know which team they are in and who are the group members.
As a teaching Assistant, I can calculate and enter grades for team assignments, quizzes, and exams for students so that it can be entered into the system.
As a teaching Assistant, I can view average grades including highest and lowest, and for team assignments, quizzes, and exams so that I can better understand the overall performance of the students in the course and identify areas where additional support or intervention may be needed.
As a teaching Assistant, I can view the grades of particular students so that I can provide personalized support and guidance to the student.
